#!/usr/bin/env python3
# Regenerate campfire_frames.h from Campfire_Animated.png.
# Pipeline: composite on black -> 4x LANCZOS upscale -> per-frame portrait crop
# (122x250) -> rotate 90 deg CCW (flames point left, fills 250x122 landscape)
# -> Bayer 4x4 ordered dither (aligned to display pixel grid, no gamma) ->
# pack as LSB-first XBitmap with inverted bit semantics (bit=1 = black ink on
# the canvas, bit=0 = leave white canvas through -> flame).

from PIL import Image
import sys, pathlib

HERE = pathlib.Path(__file__).resolve().parent
SRC  = HERE / "Campfire_Animated.png"
OUT  = HERE / "campfire_frames.h"

FRAME_COUNT     = 7
DISP_W, DISP_H  = 250, 122           # full panel, flames pointing left

# Bayer 4x4 ordered-dither matrix, thresholds in [0..255]:
#   t = B * 16 + 8   so the ladder is [8, 24, 40, ..., 248] step 16.
_BAYER = [[ 0,  8,  2, 10],
          [12,  4, 14,  6],
          [ 3, 11,  1,  9],
          [15,  7, 13,  5]]
_THR   = [[_BAYER[y][x] * 16 + 8 for x in range(4)] for y in range(4)]

def bayer_dither(img):
    w, h = img.size
    px = img.load()
    out = Image.new("1", (w, h))
    op  = out.load()
    for y in range(h):
        for x in range(w):
            op[x, y] = 255 if px[x, y] > _THR[y & 3][x & 3] else 0
    return out

def pack_lsb_first_inverted(img1):
    """Pack a PIL mode-'1' image as LSB-first, row-major,
    ((w+7)//8) bytes per row -- the format Adafruit_GFX::drawXBitmap reads.
    INVERTED semantics: image white pixel (flame) -> bit=0, image black
    pixel (background) -> bit=1. drawXBitmap(..., color=1) on the default
    white canvas then paints bit=1 cells black, leaving flame pixels as
    the bare canvas -> white flames on black background."""
    w, h = img1.size
    row_bytes = (w + 7) // 8
    px = img1.load()
    out = bytearray(row_bytes * h)
    for y in range(h):
        for x in range(w):
            if not px[x, y]:                       # source black -> bit set (ink)
                out[y * row_bytes + (x >> 3)] |= (1 << (x & 7))
    return bytes(out)

def emit_c_array(name, data, cols=12):
    lines = [f"    /* {name} */"]
    for i in range(0, len(data), cols):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + cols])
        lines.append("    " + chunk + ",")
    return "\n".join(lines)

def main():
    if not SRC.exists():
        print(f"ERROR: {SRC} not found", file=sys.stderr); sys.exit(1)

    src   = Image.open(SRC).convert("RGBA")
    black = Image.new("RGBA", src.size, (0, 0, 0, 255))
    gray  = Image.alpha_composite(black, src).convert("L")

    # 4x LANCZOS upscale so Bayer has enough pixels to express full tonal range.
    gray4x = gray.resize((gray.size[0] * 4, gray.size[1] * 4), Image.LANCZOS)

    # Per-frame portrait crop (122x250) -> rotate 90 CCW -> 250x122 landscape.
    FRAME_W_4X, FRAME_H_4X = 128, 256
    PORT_W, PORT_H = 122, 250
    pad_x = (FRAME_W_4X - PORT_W) // 2   # 3
    pad_y = (FRAME_H_4X - PORT_H) // 2   # 3

    frames_packed = []
    for i in range(FRAME_COUNT):
        fx0 = i * FRAME_W_4X + pad_x
        fy0 = pad_y
        portrait  = gray4x.crop((fx0, fy0, fx0 + PORT_W, fy0 + PORT_H))   # 122x250
        landscape = portrait.transpose(Image.ROTATE_90)                   # 250x122, flames -> left
        assert landscape.size == (DISP_W, DISP_H), landscape.size
        dithered  = bayer_dither(landscape)                               # Bayer aligned to display grid
        frames_packed.append(pack_lsb_first_inverted(dithered))

    frame_bytes = ((DISP_W + 7) // 8) * DISP_H
    assert len(frames_packed[0]) == frame_bytes == 32 * 122 == 3904

    parts = [
        "// Generated by convert.py from Campfire_Animated.png. Do not edit by hand.",
        "// 4x LANCZOS upscale, 90deg CCW rotation, Bayer 4x4 dither (aligned to panel grid).",
        "// Full-screen 250x122 frames, flames pointing left.",
        "// Bit semantics: bit=1 = background (black ink); bit=0 = flame (white canvas).",
        "// Draw with: drawXBitmap(0, 0, frame, 250, 122, 1).",
        "",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"#define CAMPFIRE_FRAME_W      {DISP_W}",
        f"#define CAMPFIRE_FRAME_H      {DISP_H}",
        f"#define CAMPFIRE_FRAME_COUNT  {FRAME_COUNT}",
        f"#define CAMPFIRE_FRAME_BYTES  {frame_bytes}",
        "",
        f"static const uint8_t campfire_frames[CAMPFIRE_FRAME_COUNT][CAMPFIRE_FRAME_BYTES] = {{",
    ]
    for i, f in enumerate(frames_packed):
        parts.append("  {")
        parts.append(emit_c_array(f"frame {i}", f))
        parts.append("  },")
    parts.append("};")
    parts.append("")
    OUT.write_text("\n".join(parts), encoding="ascii")
    print(f"Wrote {OUT} ({OUT.stat().st_size} bytes)")

if __name__ == "__main__":
    main()
